const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');

const PORT = Number(process.env.PORT || 3000);
const DB_PATH = process.env.DB_PATH || path.join(__dirname, 'data', 'warehouse.sqlite');
fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });
const db = new DatabaseSync(DB_PATH);
db.exec('PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL;');
db.exec(`
CREATE TABLE IF NOT EXISTS warehouses(id TEXT PRIMARY KEY, name TEXT NOT NULL, location TEXT NOT NULL DEFAULT '', active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)));
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL DEFAULT '蔬菜', unit TEXT NOT NULL DEFAULT '箱', min_stock INTEGER NOT NULL DEFAULT 0 CHECK(min_stock >= 0), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)));
CREATE TABLE IF NOT EXISTS locations(id INTEGER PRIMARY KEY AUTOINCREMENT, warehouse_id TEXT NOT NULL REFERENCES warehouses(id), code TEXT NOT NULL, capacity INTEGER CHECK(capacity IS NULL OR capacity >= 0), UNIQUE(warehouse_id,code));
CREATE TABLE IF NOT EXISTS product_locations(product_id TEXT NOT NULL REFERENCES products(id), location_id INTEGER NOT NULL REFERENCES locations(id), PRIMARY KEY(product_id,location_id));
CREATE TABLE IF NOT EXISTS batches(id TEXT PRIMARY KEY, warehouse_id TEXT NOT NULL REFERENCES warehouses(id), product_id TEXT NOT NULL REFERENCES products(id), location_id INTEGER NOT NULL REFERENCES locations(id), quantity INTEGER NOT NULL CHECK(quantity >= 0), received_at TEXT NOT NULL, expiry_date TEXT);
CREATE TABLE IF NOT EXISTS transactions(id INTEGER PRIMARY KEY AUTOINCREMENT, type TEXT NOT NULL CHECK(type IN ('inbound','outbound','scrap','stocktake')), warehouse_id TEXT NOT NULL REFERENCES warehouses(id), product_id TEXT NOT NULL REFERENCES products(id), batch_id TEXT REFERENCES batches(id), quantity INTEGER NOT NULL CHECK(quantity > 0), reason TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, operator TEXT NOT NULL DEFAULT '李太太', voided_at TEXT);
CREATE TABLE IF NOT EXISTS stocktakes(id INTEGER PRIMARY KEY AUTOINCREMENT, warehouse_id TEXT NOT NULL REFERENCES warehouses(id), created_at TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('draft','confirmed')));
CREATE TABLE IF NOT EXISTS stocktake_lines(id INTEGER PRIMARY KEY AUTOINCREMENT, stocktake_id INTEGER NOT NULL REFERENCES stocktakes(id), batch_id TEXT NOT NULL REFERENCES batches(id), system_quantity INTEGER NOT NULL, actual_quantity INTEGER NOT NULL, difference INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS transfer_sheets(id TEXT PRIMARY KEY, warehouse_id TEXT NOT NULL REFERENCES warehouses(id), product_id TEXT NOT NULL REFERENCES products(id), quantity INTEGER NOT NULL CHECK(quantity>0), status TEXT NOT NULL CHECK(status IN ('open','completed','shipped')), created_at TEXT NOT NULL, completed_at TEXT);
CREATE TABLE IF NOT EXISTS transfer_sheet_lines(id INTEGER PRIMARY KEY AUTOINCREMENT, transfer_sheet_id TEXT NOT NULL REFERENCES transfer_sheets(id), batch_id TEXT NOT NULL REFERENCES batches(id), quantity INTEGER NOT NULL CHECK(quantity>0), UNIQUE(transfer_sheet_id,batch_id));
CREATE INDEX IF NOT EXISTS idx_batches_fifo ON batches(warehouse_id,product_id,received_at,id);
CREATE INDEX IF NOT EXISTS idx_transactions_created ON transactions(created_at DESC);
`);
try { db.exec('ALTER TABLE transactions ADD COLUMN voided_at TEXT'); }
catch (e) { if (!String(e.message).includes('duplicate column name')) throw e; }
try { db.exec('ALTER TABLE locations ADD COLUMN capacity INTEGER CHECK(capacity IS NULL OR capacity >= 0)'); }
catch (e) { if (!String(e.message).includes('duplicate column name')) throw e; }

const seeded = db.prepare('SELECT COUNT(*) n FROM warehouses').get().n;
if (!seeded) seed();
// Existing demo batches define each product's permitted storage locations.
db.exec('INSERT OR IGNORE INTO product_locations(product_id,location_id) SELECT DISTINCT b.product_id,b.location_id FROM batches b');

function now() { return new Date().toISOString(); }
function seed() {
  const insertWarehouse = db.prepare('INSERT INTO warehouses(id,name,location) VALUES(?,?,?)');
  insertWarehouse.run('W01','竹南冷凍倉庫1','竹南'); insertWarehouse.run('W02','竹南冷凍倉庫2','竹南');
  const insertProduct = db.prepare('INSERT INTO products(id,name,category,unit,min_stock) VALUES(?,?,?,?,?)');
  [['P001','甘藍菜','蔬菜','箱',5],['P002','青江菜','蔬菜','箱',5],['P003','高麗菜','蔬菜','箱',5],['P004','玉米','蔬菜','箱',3]].forEach(x=>insertProduct.run(...x));
  const loc = db.prepare('INSERT INTO locations(warehouse_id,code,capacity) VALUES(?,?,20)');
  const batch = db.prepare('INSERT INTO batches(id,warehouse_id,product_id,location_id,quantity,received_at) VALUES(?,?,?,?,?,?)');
  const txn = db.prepare("INSERT INTO transactions(type,warehouse_id,product_id,batch_id,quantity,reason,created_at) VALUES('inbound',?,?,?,?,?,?)");
  const add=(wh,prod,code,qty,date,id)=>{loc.run(wh,code);const lid=db.prepare('SELECT id FROM locations WHERE warehouse_id=? AND code=?').get(wh,code).id;batch.run(id,wh,prod,lid,qty,date);txn.run(wh,prod,id,qty,'Demo 初始庫存',date);};
  add('W01','P001','A01',5,'2026-09-24T09:00:00.000Z','B20260924001');
  add('W01','P002','A02',3,'2026-09-25T01:00:00.000Z','B20260925001');
  add('W01','P002','A05',5,'2026-09-28T02:00:00.000Z','B20260928001');
  add('W01','P003','A03',8,'2026-09-24T09:00:00.000Z','B20260924002');
  add('W02','P001','B01',4,'2026-09-24T09:00:00.000Z','B20260924003');
  add('W02','P002','B02',5,'2026-09-26T06:00:00.000Z','B20260926001');
  add('W02','P004','B03',6,'2026-09-27T06:00:00.000Z','B20260927001');
}

const inventorySQL = `SELECT b.id batch_id,w.id warehouse_id,w.name warehouse,p.id product_id,p.name product,p.unit,l.code location,b.quantity,b.received_at,b.expiry_date,(SELECT t.reason FROM transactions t WHERE t.batch_id=b.id AND t.type='inbound' AND t.voided_at IS NULL ORDER BY t.id DESC LIMIT 1) inbound_reason,(SELECT b2.id FROM batches b2 JOIN transactions t2 ON t2.batch_id=b2.id WHERE b2.warehouse_id=b.warehouse_id AND b2.product_id=b.product_id AND t2.type='inbound' AND t2.voided_at IS NULL ORDER BY b2.received_at DESC,t2.id DESC LIMIT 1)=b.id is_latest_inbound,EXISTS(SELECT 1 FROM transactions t WHERE t.batch_id=b.id AND t.type='inbound' AND t.voided_at IS NULL) can_delete FROM batches b JOIN warehouses w ON w.id=b.warehouse_id JOIN products p ON p.id=b.product_id JOIN locations l ON l.id=b.location_id WHERE b.quantity>0`;
function inventory(query={}) {
  let sql=inventorySQL, args=[], clauses=[];
  if(query.warehouse) { clauses.push('w.id=?'); args.push(query.warehouse); }
  if(query.search) { clauses.push('(p.name LIKE ? OR p.id LIKE ? OR l.code LIKE ?)'); args.push(...Array(3).fill(`%${query.search}%`)); }
  if(clauses.length) sql+=` AND ${clauses.join(' AND ')}`;
  return db.prepare(sql+' ORDER BY w.id,p.name,b.received_at,b.id').all(...args);
}
function getInventoryOverview() {
  const warehouses=db.prepare(`SELECT w.id,w.name,COALESCE(SUM(b.quantity),0) quantity FROM warehouses w LEFT JOIN batches b ON b.warehouse_id=w.id GROUP BY w.id ORDER BY w.id`).all();
  const lines=db.prepare(`SELECT w.id warehouse_id,p.id product_id,p.name product,p.unit,l.code location,SUM(b.quantity) quantity FROM batches b JOIN warehouses w ON w.id=b.warehouse_id JOIN products p ON p.id=b.product_id JOIN locations l ON l.id=b.location_id WHERE b.quantity>0 GROUP BY w.id,p.id,l.id ORDER BY w.id,p.name,l.code`).all();
  const sections=warehouses.map(w=>({id:w.id,name:w.name,quantity:w.quantity,items:lines.filter(line=>line.warehouse_id===w.id)}));
  return {warehouses:sections,totalQuantity:sections.reduce((sum,w)=>sum+w.quantity,0)};
}
function error(status,message,extra={}) { const e=new Error(message);e.status=status;Object.assign(e,extra);throw e; }
function body(req) { return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>1e6)reject(new Error('Request too large'));});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'));}catch{reject(new Error('請提供有效的 JSON 資料'));}});req.on('error',reject);}); }
function json(res,status,data) {res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*'});res.end(JSON.stringify(data));}
function transaction(fn) { db.exec('BEGIN IMMEDIATE');try{const result=fn();db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;} }
function positive(value,label='數量') {const n=Number(value);if(!Number.isSafeInteger(n)||n<=0)error(400,`${label}必須是正整數`);return n;}
function parseReceivedAt(value) {if(!value)error(400,'請輸入進貨時間');const date=new Date(value);if(Number.isNaN(date.getTime()))error(400,'進貨時間格式不正確');return date.toISOString();}
function fifoPlan(warehouse,product,qty) {const rows=warehouse?db.prepare('SELECT * FROM batches WHERE warehouse_id=? AND product_id=? AND quantity>0 ORDER BY received_at,id').all(warehouse,product):db.prepare('SELECT * FROM batches WHERE product_id=? AND quantity>0 ORDER BY received_at,id,warehouse_id').all(product);const available=rows.reduce((sum,row)=>sum+row.quantity,0);if(available<qty)error(409,`庫存不足，目前兩座倉庫合計只有 ${available} 箱，無法出貨 ${qty} 箱。`,{available});let remain=qty;return rows.flatMap(batch=>{if(remain<=0)return [];const quantity=Math.min(remain,batch.quantity);remain-=quantity;return [{batchId:batch.id,quantity,batch}]})}
function getSummary() {
  const warehouses=db.prepare('SELECT w.id,w.name,COALESCE(SUM(b.quantity),0) quantity FROM warehouses w LEFT JOIN batches b ON b.warehouse_id=w.id GROUP BY w.id ORDER BY w.id').all();
  const today=new Date().toISOString().slice(0,10);
  const counts=db.prepare("SELECT SUM(type='inbound') inbound,SUM(type='outbound') outbound FROM transactions WHERE substr(created_at,1,10)=?").get(today);
  return {warehouses,todayInbound:counts.inbound||0,todayOutbound:counts.outbound||0,products:db.prepare('SELECT * FROM products ORDER BY id').all()};
}
function handle(req,res) {
  if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});return res.end();}
  const url=new URL(req.url,'http://localhost');
  try {
    if(req.method==='GET'&&url.pathname==='/api/summary')return json(res,200,getSummary());
    if(req.method==='GET'&&url.pathname==='/api/inventory/overview')return json(res,200,getInventoryOverview());
    if(req.method==='GET'&&url.pathname==='/api/warehouses')return json(res,200,db.prepare('SELECT * FROM warehouses ORDER BY id').all());
    if(req.method==='GET'&&url.pathname==='/api/products')return json(res,200,db.prepare('SELECT * FROM products ORDER BY id').all());
    if(req.method==='GET'&&url.pathname==='/api/locations'){
      const warehouse=url.searchParams.get('warehouse'),product=url.searchParams.get('product');
      const select=`SELECT l.id,l.warehouse_id,l.code,l.capacity,w.name warehouse,COALESCE(SUM(b.quantity),0) quantity FROM locations l JOIN warehouses w ON w.id=l.warehouse_id LEFT JOIN batches b ON b.location_id=l.id`;
      if(warehouse&&product)return json(res,200,db.prepare(`${select} JOIN product_locations pl ON pl.location_id=l.id WHERE l.warehouse_id=? AND pl.product_id=? GROUP BY l.id ORDER BY l.code`).all(warehouse,product));
      return json(res,200,db.prepare(`${select} GROUP BY l.id ORDER BY w.id,l.code`).all());
    }
    if(req.method==='GET'&&url.pathname==='/api/storage-capacity')return json(res,200,db.prepare(`SELECT w.id warehouse_id,p.id product_id,COALESCE(SUM(CASE WHEN l.capacity IS NOT NULL THEN MAX(l.capacity-COALESCE(stock.quantity,0),0) ELSE 0 END),0) available_capacity,COUNT(l.id) location_count FROM warehouses w CROSS JOIN products p LEFT JOIN product_locations pl ON pl.product_id=p.id LEFT JOIN locations l ON l.id=pl.location_id AND l.warehouse_id=w.id LEFT JOIN (SELECT location_id,SUM(quantity) quantity FROM batches GROUP BY location_id) stock ON stock.location_id=l.id GROUP BY w.id,p.id ORDER BY w.id,p.id`).all());
    if(req.method==='PATCH'&&url.pathname.match(/^\/api\/locations\/\d+$/)) {body(req).then(data=>{const capacity=Number(data.capacity),id=Number(url.pathname.split('/').pop());if(data.capacity==null||String(data.capacity).trim()===''||!Number.isSafeInteger(capacity)||capacity<0)error(400,'儲位上限需為零或正整數');const result=transaction(()=>{const location=db.prepare('SELECT id,code FROM locations WHERE id=?').get(id);if(!location)error(404,'找不到此儲位');const quantity=db.prepare('SELECT COALESCE(SUM(quantity),0) quantity FROM batches WHERE location_id=?').get(id).quantity;if(capacity<quantity)error(409,`新上限不能低於目前庫存 ${quantity} 箱`);db.prepare('UPDATE locations SET capacity=? WHERE id=?').run(capacity,id);return {id,capacity,quantity};});json(res,200,result);}).catch(e=>json(res,e.status||400,{error:e.message}));return;}
    if(req.method==='POST'&&url.pathname==='/api/warehouses') {body(req).then(data=>{const id=String(data.id||'').trim().toUpperCase(),name=String(data.name||'').trim();if(!/^W[0-9A-Z]{2,8}$/.test(id)||!name)error(400,'倉庫編號需以 W 開頭，並填寫倉庫名稱');db.prepare('INSERT INTO warehouses(id,name,location) VALUES(?,?,?)').run(id,name,String(data.location||'').trim());json(res,201,{id,name});}).catch(e=>json(res,e.status||409,{error:e.message.includes('UNIQUE')?'倉庫編號已存在':e.message}));return;}
    if(req.method==='POST'&&url.pathname==='/api/products') {body(req).then(data=>{const id=String(data.id||'').trim().toUpperCase(),name=String(data.name||'').trim(),min=Number(data.minStock||0);if(!/^P[0-9A-Z]{2,8}$/.test(id)||!name)error(400,'商品編號需以 P 開頭，並填寫商品名稱');if(!Number.isSafeInteger(min)||min<0)error(400,'最低庫存需為零或正整數');db.prepare('INSERT INTO products(id,name,category,unit,min_stock) VALUES(?,?,?,?,?)').run(id,name,String(data.category||'蔬菜').trim(),String(data.unit||'箱').trim(),min);json(res,201,{id,name});}).catch(e=>json(res,e.status||409,{error:e.message.includes('UNIQUE')?'商品編號已存在':e.message}));return;}
    if(req.method==='POST'&&url.pathname==='/api/locations') {body(req).then(data=>{const code=String(data.code||'').trim().toUpperCase(),capacity=data.capacity==null?20:Number(data.capacity);if(!db.prepare('SELECT 1 FROM warehouses WHERE id=?').get(data.warehouse))error(400,'請選擇有效倉庫');if(!code)error(400,'請輸入儲位代碼');if(data.capacity!=null&&String(data.capacity).trim()==='')error(400,'請輸入有效的儲位箱數上限');if(!Number.isSafeInteger(capacity)||capacity<0)error(400,'請輸入有效的儲位箱數上限');if(data.product&&!db.prepare('SELECT 1 FROM products WHERE id=?').get(data.product))error(400,'請選擇有效商品');transaction(()=>{db.prepare('INSERT OR IGNORE INTO locations(warehouse_id,code,capacity) VALUES(?,?,?)').run(data.warehouse,code,capacity);const location=db.prepare('SELECT id,capacity FROM locations WHERE warehouse_id=? AND code=?').get(data.warehouse,code);if(location.capacity===null)db.prepare('UPDATE locations SET capacity=? WHERE id=?').run(capacity,location.id);if(data.product){const exists=db.prepare('SELECT 1 FROM product_locations WHERE product_id=? AND location_id=?').get(data.product,location.id);if(exists)error(409,'此商品已設定此儲位');db.prepare('INSERT INTO product_locations(product_id,location_id) VALUES(?,?)').run(data.product,location.id);}else if(db.prepare('SELECT 1 FROM batches b JOIN locations l ON l.id=b.location_id WHERE l.warehouse_id=? AND l.code=?').get(data.warehouse,code))error(409,'儲位已存在，請選擇商品以新增商品與儲位的對應');});json(res,201,{warehouse:data.warehouse,code,capacity,product:data.product||null});}).catch(e=>json(res,e.status||409,{error:e.message.includes('UNIQUE')?'此倉庫已經有相同儲位':e.message}));return;}
    if(req.method==='GET'&&url.pathname==='/api/inventory')return json(res,200,inventory({warehouse:url.searchParams.get('warehouse'),search:url.searchParams.get('search')}));
    if(req.method==='GET'&&url.pathname==='/api/transactions')return json(res,200,db.prepare(`SELECT t.*,w.name warehouse,p.name product,p.unit,b.id batch,l.code location,CASE WHEN t.type='inbound' AND t.id=(SELECT t2.id FROM transactions t2 JOIN batches b2 ON b2.id=t2.batch_id WHERE t2.type='inbound' AND t2.voided_at IS NULL AND t2.warehouse_id=t.warehouse_id AND t2.product_id=t.product_id ORDER BY b2.received_at DESC,t2.id DESC LIMIT 1) THEN 1 ELSE 0 END is_latest_inbound FROM transactions t JOIN warehouses w ON w.id=t.warehouse_id JOIN products p ON p.id=t.product_id LEFT JOIN batches b ON b.id=t.batch_id LEFT JOIN locations l ON l.id=b.location_id WHERE t.voided_at IS NULL ORDER BY t.created_at DESC,t.id DESC LIMIT 500`).all());
    if(req.method==='POST'&&url.pathname==='/api/inbounds') {body(req).then(data=>{const qty=positive(data.quantity),locCode=String(data.location||'').trim().toUpperCase(),receivedAt=parseReceivedAt(data.receivedAt);if(!locCode)error(400,'請選擇存放儲位');if(!db.prepare('SELECT 1 FROM warehouses WHERE id=?').get(data.warehouse))error(400,'請選擇有效倉庫');if(!db.prepare('SELECT 1 FROM products WHERE id=?').get(data.product))error(400,'請選擇有效商品');const createdAt=now(),batchId=`B${createdAt.replace(/\D/g,'').slice(0,14)}${String(db.prepare('SELECT COUNT(*) n FROM batches').get().n+1).padStart(3,'0')}`;const result=transaction(()=>{const loc=db.prepare('SELECT l.id,l.code,l.capacity,COALESCE(SUM(b.quantity),0) quantity FROM locations l JOIN product_locations pl ON pl.location_id=l.id LEFT JOIN batches b ON b.location_id=l.id WHERE l.warehouse_id=? AND l.code=? AND pl.product_id=? GROUP BY l.id').get(data.warehouse,locCode,data.product);if(!loc)error(400,'此商品不可存放在該儲位，請從可用儲位選單中選擇');if(loc.capacity===null)error(409,`儲位 ${loc.code} 尚未設定箱數上限，請到基本資料設定後再進貨`);if(loc.quantity+qty>loc.capacity)error(409,`儲位 ${loc.code} 庫存已滿：上限 ${loc.capacity} 箱、現有 ${loc.quantity} 箱，無法再放 ${qty} 箱`);db.prepare('INSERT INTO batches(id,warehouse_id,product_id,location_id,quantity,received_at,expiry_date) VALUES(?,?,?,?,?,?,?)').run(batchId,data.warehouse,data.product,loc.id,qty,receivedAt,null);db.prepare("INSERT INTO transactions(type,warehouse_id,product_id,batch_id,quantity,reason,created_at) VALUES('inbound',?,?,?,?,?,?)").run(data.warehouse,data.product,batchId,qty,String(data.reason||'').trim()||'新進貨',createdAt);return {batchId,receivedAt,quantity:qty};});json(res,201,result);}).catch(e=>json(res,e.status||400,{error:e.message}));return;}
    if(req.method==='DELETE'&&url.pathname.match(/^\/api\/inbounds\/[^/]+$/)) {const batchId=decodeURIComponent(url.pathname.split('/').pop());try{const result=transaction(()=>{const batch=db.prepare('SELECT * FROM batches WHERE id=?').get(batchId);if(!batch)error(404,'找不到這筆進貨批次');const inbound=db.prepare("SELECT id FROM transactions WHERE batch_id=? AND type='inbound' AND voided_at IS NULL").get(batchId);if(!inbound)error(404,'此批次的進貨紀錄已不存在');const qty=batch.quantity,createdAt=now();db.prepare("UPDATE stocktake_lines SET system_quantity=0,actual_quantity=0,difference=0 WHERE batch_id=? AND stocktake_id IN (SELECT id FROM stocktakes WHERE status='draft')").run(batchId);db.prepare('UPDATE batches SET quantity=0 WHERE id=?').run(batchId);db.prepare('UPDATE transactions SET voided_at=? WHERE id=?').run(createdAt,inbound.id);if(qty>0)db.prepare("INSERT INTO transactions(type,warehouse_id,product_id,batch_id,quantity,reason,created_at) VALUES('stocktake',?,?,?,?,?,?)").run(batch.warehouse_id,batch.product_id,batchId,qty,`撤銷誤登進貨 ${batchId}`,createdAt);return {batchId,removedQuantity:qty};});return json(res,200,result);}catch(e){return json(res,e.status||400,{error:e.message});}}
    if(req.method==='POST'&&url.pathname==='/api/transfer-sheets') {body(req).then(data=>{const qty=positive(data.quantity);if(!db.prepare('SELECT 1 FROM products WHERE id=?').get(data.product))error(400,'請選擇有效商品');const createdAt=now();const sheet=transaction(()=>{const plan=fifoPlan(null,data.product,qty),id=`T${createdAt.replace(/\D/g,'').slice(0,14)}${String(db.prepare('SELECT COUNT(*) n FROM transfer_sheets').get().n+1).padStart(3,'0')}`;db.prepare("INSERT INTO transfer_sheets(id,warehouse_id,product_id,quantity,status,created_at) VALUES(?,?,?,?,'open',?)").run(id,plan[0].batch.warehouse_id,data.product,qty,createdAt);const add=db.prepare('INSERT INTO transfer_sheet_lines(transfer_sheet_id,batch_id,quantity) VALUES(?,?,?)');const lines=plan.map(item=>{add.run(id,item.batchId,item.quantity);return {batchId:item.batchId,quantity:item.quantity,location:db.prepare('SELECT code FROM locations WHERE id=?').get(item.batch.location_id).code,warehouse_id:item.batch.warehouse_id,warehouse:db.prepare('SELECT name FROM warehouses WHERE id=?').get(item.batch.warehouse_id).name,receivedAt:item.batch.received_at}});return {id,warehouse:'全部倉庫',product:data.product,quantity:qty,status:'open',createdAt,lines}});json(res,201,sheet)}).catch(e=>json(res,e.status||400,{error:e.message,available:e.available}));return;}
    if(req.method==='POST'&&url.pathname.match(/^\/api\/transfer-sheets\/[^/]+\/complete$/)) {body(req).then(data=>{if(data.completed!==true)error(400,'請勾選搬運單已完成');const id=decodeURIComponent(url.pathname.split('/')[3]),timestamp=now();const result=transaction(()=>{const sheet=db.prepare('SELECT * FROM transfer_sheets WHERE id=?').get(id);if(!sheet)error(404,'找不到搬運單');if(sheet.status!=='open')error(409,'此搬運單已完成或已出貨，請重新產生搬運單');const planned=db.prepare('SELECT batch_id batchId,quantity FROM transfer_sheet_lines WHERE transfer_sheet_id=? ORDER BY id').all(id),current=fifoPlan(null,sheet.product_id,sheet.quantity);if(current.length!==planned.length||current.some((item,i)=>item.batchId!==planned[i].batchId||item.quantity!==planned[i].quantity))error(409,'庫存批次已變動，請重新產生搬運單');const scanned=Array.isArray(data.pickedBatches)?data.pickedBatches.map(item=>({batchId:String(item.batchId||'').trim().toUpperCase(),quantity:Number(item.quantity)})):[];if(scanned.length!==planned.length||planned.some((item,i)=>scanned[i].batchId!==item.batchId.toUpperCase()||scanned[i].quantity!==item.quantity))error(409,'掃描批次或箱數與搬運單不符，搬運單尚未完成');db.prepare("UPDATE transfer_sheets SET status='completed',completed_at=? WHERE id=? AND status='open'").run(timestamp,id);return {id,status:'completed',completedAt:timestamp}});json(res,200,result)}).catch(e=>json(res,e.status||400,{error:e.message,available:e.available}));return;}
    if(req.method==='POST'&&url.pathname==='/api/outbounds') {body(req).then(data=>{const qty=positive(data.quantity),timestamp=now(),sheetId=String(data.transferSheetId||'');if(!sheetId)error(409,'請先產生搬運單並完成勾選才可出貨');const picks=transaction(()=>{const sheet=db.prepare('SELECT * FROM transfer_sheets WHERE id=?').get(sheetId);if(!sheet)error(404,'找不到搬運單，請重新產生');if(sheet.status!=='completed')error(409,'搬運單尚未完成勾選');if(sheet.product_id!==data.product||sheet.quantity!==qty)error(409,'出貨內容與已完成的搬運單不符');const plan=fifoPlan(null,data.product,qty),planned=db.prepare('SELECT batch_id batchId,quantity FROM transfer_sheet_lines WHERE transfer_sheet_id=? ORDER BY id').all(sheetId),scanned=Array.isArray(data.pickedBatches)?data.pickedBatches.map(x=>({batchId:String(x.batchId||'').trim().toUpperCase(),quantity:Number(x.quantity)})):[];if(plan.length!==planned.length||plan.some((item,i)=>item.batchId!==planned[i].batchId||item.quantity!==planned[i].quantity))error(409,'庫存批次已變動，請重新產生搬運單');if(scanned.length!==planned.length||planned.some((item,i)=>scanned[i].batchId!==item.batchId.toUpperCase()||scanned[i].quantity!==item.quantity))error(409,'實際掃描內容與搬運單不符，庫存尚未扣帳');const out=[];for(const item of plan){const b=item.batch;db.prepare('UPDATE batches SET quantity=quantity-? WHERE id=? AND quantity>=?').run(item.quantity,b.id,item.quantity);db.prepare("INSERT INTO transactions(type,warehouse_id,product_id,batch_id,quantity,reason,created_at) VALUES('outbound',?,?,?,?,?,?)").run(b.warehouse_id,b.product_id,b.id,item.quantity,data.reason||'客戶訂單',timestamp);out.push({batchId:b.id,location:db.prepare('SELECT code FROM locations WHERE id=?').get(b.location_id).code,warehouse_id:b.warehouse_id,warehouse:db.prepare('SELECT name FROM warehouses WHERE id=?').get(b.warehouse_id).name,quantity:item.quantity,receivedAt:b.received_at});}db.prepare("UPDATE transfer_sheets SET status='shipped' WHERE id=? AND status='completed'").run(sheetId);return out});json(res,201,{quantity:qty,picks,transferSheetId:sheetId,outboundAt:timestamp})}).catch(e=>json(res,e.status||400,{error:e.message,available:e.available}));return;}
    if(req.method==='POST'&&url.pathname==='/api/scraps') {body(req).then(data=>{const qty=positive(data.quantity);const reason=String(data.reason||'').trim();if(!reason)error(400,'請填寫報廢原因');if(data.reasonCategory==='其他'&&(!data.reasonOther||!String(data.reasonOther).trim()))error(400,'請填寫其他報廢原因');const batch=db.prepare('SELECT * FROM batches WHERE id=? AND warehouse_id=? AND product_id=?').get(data.batchId,data.warehouse,data.product);if(!batch)error(404,'找不到指定庫存批次');if(batch.quantity<qty)error(409,`該批次只有 ${batch.quantity} 箱，不能報廢 ${qty} 箱。`);const timestamp=now();transaction(()=>{db.prepare('UPDATE batches SET quantity=quantity-? WHERE id=? AND quantity>=?').run(qty,batch.id,qty);db.prepare("INSERT INTO transactions(type,warehouse_id,product_id,batch_id,quantity,reason,created_at) VALUES('scrap',?,?,?,?,?,?)").run(batch.warehouse_id,batch.product_id,batch.id,qty,reason,timestamp);});json(res,201,{quantity:qty,batchId:batch.id,remaining:batch.quantity-qty,createdAt:timestamp});}).catch(e=>json(res,e.status||400,{error:e.message}));return;}
    if(req.method==='POST'&&url.pathname==='/api/stocktakes') {body(req).then(data=>{if(!db.prepare('SELECT 1 FROM warehouses WHERE id=?').get(data.warehouse))error(400,'請選擇有效倉庫');const timestamp=now();const created=transaction(()=>{const stocktakeId=Number(db.prepare("INSERT INTO stocktakes(warehouse_id,created_at,status) VALUES(?,?,'draft')").run(data.warehouse,timestamp).lastInsertRowid);const lines=db.prepare('SELECT b.id batch_id,b.quantity system_quantity,p.name product,l.code location FROM batches b JOIN products p ON p.id=b.product_id JOIN locations l ON l.id=b.location_id WHERE b.warehouse_id=? AND b.quantity>0 ORDER BY b.id').all(data.warehouse);const add=db.prepare('INSERT INTO stocktake_lines(stocktake_id,batch_id,system_quantity,actual_quantity,difference) VALUES(?,?,?,?,0)');lines.forEach(l=>add.run(stocktakeId,l.batch_id,l.system_quantity,l.system_quantity));return {id:stocktakeId,warehouse:data.warehouse,createdAt:timestamp,lines};});json(res,201,created);}).catch(e=>json(res,e.status||400,{error:e.message}));return;}
    if(req.method==='POST'&&url.pathname.match(/^\/api\/stocktakes\/\d+\/confirm$/)) {body(req).then(data=>{const id=Number(url.pathname.split('/')[3]);const head=db.prepare("SELECT * FROM stocktakes WHERE id=? AND status='draft'").get(id);if(!head)error(404,'找不到待確認的盤點單');const lines=db.prepare('SELECT * FROM stocktake_lines WHERE stocktake_id=?').all(id);const actual=data.actual||{};transaction(()=>{for(const line of lines){const value=actual[line.batch_id]??line.system_quantity;const qty=Number(value);if(!Number.isSafeInteger(qty)||qty<0)error(400,'實際數量必須是零或正整數');const diff=qty-line.system_quantity;db.prepare('UPDATE stocktake_lines SET actual_quantity=?,difference=? WHERE id=?').run(qty,diff,line.id);if(diff){const b=db.prepare('SELECT * FROM batches WHERE id=?').get(line.batch_id);if(qty===0)db.prepare('UPDATE batches SET quantity=0 WHERE id=?').run(b.id);else db.prepare('UPDATE batches SET quantity=? WHERE id=?').run(qty,b.id);db.prepare("INSERT INTO transactions(type,warehouse_id,product_id,batch_id,quantity,reason,created_at) VALUES('stocktake',?,?,?,?,?,?)").run(b.warehouse_id,b.product_id,b.id,Math.abs(diff),`盤點調整：系統 ${line.system_quantity}，實際 ${qty}`,now());}}db.prepare("UPDATE stocktakes SET status='confirmed' WHERE id=?").run(id);});json(res,200,{id,status:'confirmed',lineCount:lines.length,adjustments:lines.filter(l=>(actual[l.batch_id]??l.system_quantity)!==l.system_quantity).length});}).catch(e=>json(res,e.status||400,{error:e.message}));return;}
    if(req.method==='GET'&&url.pathname.startsWith('/api/'))return json(res,404,{error:'找不到此 API'});
    let file=url.pathname==='/'?'/index.html':url.pathname;const publicRoot=path.resolve(__dirname,'public');const resolved=path.resolve(publicRoot,`.${file}`);if(resolved!==publicRoot&&!resolved.startsWith(publicRoot+path.sep))return json(res,403,{error:'Forbidden'});fs.readFile(resolved,(err,content)=>{if(err){res.writeHead(404);return res.end('Not found');}const ext=path.extname(resolved);res.writeHead(200,{'content-type':({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'})[ext]||'application/octet-stream'});res.end(content);});
  }catch(e){json(res,e.status||500,{error:e.message});}
}

const server=http.createServer(handle);
if(require.main===module)server.listen(PORT,()=>console.log(`倉儲管理系統已啟動：http://localhost:${PORT}`));
module.exports={server,db,inventory,getInventoryOverview,getSummary,transaction,seed};
